# Этот файл используется клиентами TGS (https://github.com/tgstation/tgstation-server) для быстрой инициализации серверного экземпляра
# Формат не документирован, но надеемся его не придётся менять. По вопросам обращаться к разработчику TGS Cyberboss/@Dominion#0444
version: 1
# Версия BYOND для использования (синхронизируется с dependencies.sh через CI-задачу "TGS Test Suite")
# Должна интерпретироваться как строка, оставьте в кавычках
byond: "516.1659"
# Папки для создания в "<instance_path>/Configuration/GameStaticFiles/"
static_files:
  # Папка config должна быть статической
  - name: config
    # Указывает что папка должна быть предварительно заполнена содержимым из репозитория
    populate: true
  # Папка data должна быть статической
  - name: data
# Словарь строк. Значение - расположение файла в репозитории для загрузки в TGS. Ключ - имя файла для загрузки в "<instance_path>/Configuration/EventScripts/"
# Для серверов на Linux
linux_scripts:
  PreCompile.sh: tools/tgs_scripts/PreCompile.sh
  WatchdogLaunch.sh: tools/tgs_scripts/WatchdogLaunch.sh
  InstallDeps.sh: tools/tgs_scripts/InstallDeps.sh
# Аналогично для серверов на Windows
windows_scripts:
  PreCompile.bat: tools/tgs_scripts/PreCompile.bat
# Уровень безопасности для запуска игры
security: Trusted
