# Конфигурация фильтра чата в игре
# Формат: "слово" = "причина блокировки"
# Для мягкого фильтра причины должны быть краткими

# Блокируется везде: IC, чат мертвых, OOC
[shared]
"blockedinshared" = "Это сообщение запрещено везде, используйте другую фразу."

# Блокируется только в IC-чате (разрешено в мертвых и OOC)
[ic]
"blockedinic" = "Это сообщение запрещено в IC, используйте другую фразу."

# Блокируется в IC, кроме КПК (разрешено в КПК)
[ic_outside_pda]
"<(0_0<)" = "Танцующий Кирби запрещен на этом сервере."

# Предупреждение при использовании (везде)
[soft_shared]
"testsoftblocks" = "Вы рискуете получить бан за неправильное использование."

# Предупреждение в IC (разрешено в мертвых/OOC)
[soft_ic]
"testsofterblocks" = "Этот термин считается OOC, используйте с контекстом."

# Предупреждение в IC, кроме КПК
[soft_ic_outside_pda]
"testsoftestblocks" = "Прекратите использовать тестовые фразы в IC."
