# Режим обработки - нарезка по битовой маске
mode = "BitmaskSlice"

# Определяет типы направлений для этого DMI
# Доступно 4 варианта:
# Standard (по умолчанию) - 1 направление на кадр
# Cardinals - 4 направления на кадр (ЮГ, СЕВЕР, ВОСТОК, ЗАПАД)
# All - 8 направлений (как Cardinals + диагонали: ЮВ, ЮЗ, СВ, СЗ)
# CardinalsRotated - 1 базовое направление с автоматической ротацией
directional_strategy = "Standard"

# Сглаживание только по основным направлениям (без диагоналей)
output_type = "Cardinal"

# Размер входных блоков 32x32
[icon_size]
x = 32
y = 32

# Позиция вывода иконки (без смещения)
[output_icon_pos]
x = 0
y = 0

# Размер выходных иконок (сохранение оригинального размера)
[output_icon_size]
x = 32
y = 32

# Соответствие типов соединений номерам блоков
[positions]
convex = 0    # Нет соединений
horizontal = 1 # Горизонтальное (восток-запад)
vertical = 2   # Вертикальное (север-юг)
concave = 3    # Все направления

# Точка центра для нарезки
[cut_pos]
x = 16  # Центр по X
y = 16  # Центр по Y
