# Восстановление битовой маски (Corners)
# Позволяет легко массово извлекать шаблоны в формате PNG и их конфигурации из DMI
# Используйте этот файл, если у вас есть DMI и вам нужен редактируемый конфиг для резки
# Важно: инструмент старается, но не идеален. Нет проверки соответствия исходному DMI
# Также плохо обрабатывает переопределенные состояния (overrided states)
# Всегда проверяйте вручную (учтите, что DMI может давать расхождения в 1 RGB-значение)
mode = "BitmaskSliceReconstruct"
# Список состояний иконок для извлечения, расширен для стандартного порядка диагоналей
extract = [
    "0", "3", "12", "15", "255",
    "6-diagonal", "10-diagonal", "5-diagonal", "9-diagonal",
    "38-diagonal", "74-diagonal", "21-diagonal", "137-diagonal"
]

# Маппинг name -> state для последующего кодирования в positions list
# Позволяет извлекать конкретные состояния и использовать их для заполнения других состояний
# Полезно для переноса уникальных состояний (odd snowflake states)
#[bespoke]

# Маппинг key -> value для установки в созданный конфиг
# Позволяет задавать произвольные значения, полезно для пакетной обработки
# ВАЖНО: Предполагается, что вы зададите шаблон по умолчанию (для пакетной обработки),
# поэтому странности в работе могут быть связаны с этим
#[set]
#template = "\"bitmask/diagonal_corner_32x32\""
