# Bitmask восстановление!
# Позволяет легко массово извлекать шаблонные png и их конфиги из dmi
# Используйте это если у вас есть dmi и вам нужен конфиг для нарезки, который можно легко редактировать
# Важно: хотя система старается, она далека от идеала. Мы не проверяем соответствие исходному dmi
# И также плохо обрабатываем переопределенные состояния
# Всегда перепроверяйте (и учитывайте, что dmi странный, поэтому могут быть различия в 1 rgb значение при таком преобразовании)
mode = "BitmaskSliceReconstruct"
# Список состояний иконок для извлечения (по умолчанию)
extract = ["0", "3", "12", "15", "255"]

# Карта name -> state которая будет закодирована в positions позже
# Позволяет извлекать определенные состояния и использовать их для заполнения других состояний
# Полезно для переноса особых нестандартных состояний
#[bespoke]

# Карта key -> value для установки в создаваемом конфиге
# Позволяет устанавливать произвольные значения в создаваемый конфиг, в основном полезно для пакетной обработки
# ВАЖНО: Мы предполагаем, что вы зададите шаблон по умолчанию здесь (так как это для пакетной обработки),
# поэтому если что-то работает странно - скорее всего причина в этом
#[set]
